name: 'cleanup-test-release'
on:
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'pr to delete assets for'
        required: true
  pull_request:
    types: [closed]

env:
  version: ci-test-ignore-me-${{ github.event.inputs.pr_number || github.event.number }}
  edition: xfce
  SSH_AUTH_SOCK: /tmp/ssh_agent.sock

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: delete test-release for closed pr
        if: always()
        run: |
          echo ${{ github.token }} | gh auth login --with-token

          gh release delete ${{ env.version }} -y --repo ${{ github.repository }}
          git push --delete origin ${{ env.version }}
