name: 'build-test'
on:
  pull_request:

env:
  ##### EDIT ME #####
  iso-profiles-git: https://gitlab.manjaro.org/profiles-and-settings/iso-profiles
  version: ci-test-ignore-me-${{ github.event.number }}
  ###################

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - name: delete test-release
        run: |
          echo ${{ github.token }} | gh auth login --with-token
          gh release delete ${{ env.version }} -y --repo ${{ github.repository }} || exit 0
          git push --delete origin ${{ env.version }}
  build-release:
    runs-on: ubuntu-22.04
    needs: [cleanup]
    strategy:
      matrix:
        ##### EDIT ME #####
        EDITION: [xfce]
        BRANCH: [unstable]
        SCOPE: [minimal]
        ###################
    steps:
      - uses: styfle/cancel-workflow-action@85880fa0301c86cca9da44039ee3bb12d3bedbfa # 0.12.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4
      - id: image-build
        uses: ./
        with:
          iso-profiles-repo: ${{ env.iso-profiles-git }}
          edition: ${{ matrix.edition }}
          branch: ${{ matrix.branch }}
          scope: ${{ matrix.scope }}
          version: ${{ env.version }}
          release-tag: ${{ env.version }}
          gpg-secret-key-base64: ${{ secrets.CI_PRIV_KEY }}
          gpg-passphrase: ${{ secrets.CI_GPG_PASSPHRASE }}
          build-mirror: ${{ secrets.BUILD_MIRROR }}
